version: '3'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI port
    environment:
      - MH_STORAGE=memory
    restart: unless-stopped
